-- Script para crear 30 agencias de prueba con nueva estructura de categorías
-- Se pueden ejecutar las 3 secciones por separado si el query es muy largo

-- SECCIÓN 1: Agencias 1-10
INSERT INTO agencies (id, name, slug, description, location_city, location_region, categories, services, employees_min, employees_max, price_range, email, phone, website, is_verified, is_premium, avg_rating, reviews_count, created_at, updated_at) VALUES
(gen_random_uuid(), 'PixelLab Chile', 'pixellab-chile', 'Agencia especializada en publicidad digital y performance marketing. Expertos en Google Ads, Meta Ads y campañas programáticas.', 'Santiago', 'Región Metropolitana', ARRAY['publicidad-digital', 'estrategia-consultoria'], ARRAY['Google Ads (Search/Display/YouTube)', 'Meta Ads (Facebook/Instagram)', 'Performance Marketing'], 15, 30, '$$$', 'contacto@pixellab.cl', '+56912345001', 'https://pixellab.cl', true, true, 4.8, 12, NOW(), NOW()),
(gen_random_uuid(), 'Marca Chilena', 'marca-chilena', 'Construimos marcas memorables con identidad única. Especialistas en branding, naming y estrategia de marca.', 'Valparaíso', 'Valparaíso', ARRAY['branding-identidad', 'diseno-grafico'], ARRAY['Identidad Corporativa', 'Naming y Estrategia de Marca', 'Brandbook y Manual de Marca', 'Diseño de Logo'], 8, 15, '$$', 'hola@marcachilena.cl', '+56912345002', 'https://marcachilena.cl', true, false, 4.6, 8, NOW(), NOW()),
(gen_random_uuid(), 'WebDev Solutions', 'webdev-solutions', 'Desarrollamos sitios web y aplicaciones móviles de alto rendimiento. Especialistas en e-commerce y plataformas SaaS.', 'Santiago', 'Región Metropolitana', ARRAY['desarrollo-web'], ARRAY['Sitio Web Corporativo', 'E-commerce (Shopify/WooCommerce)', 'Desarrollo de Apps Móviles', 'Plataformas SaaS'], 12, 25, '$$$', 'contacto@webdevsolutions.cl', '+56912345003', 'https://webdevsolutions.cl', true, true, 4.9, 15, NOW(), NOW()),
(gen_random_uuid(), 'Social Boost', 'social-boost', 'Hacemos crecer tu comunidad en redes sociales con estrategias basadas en datos. Community management e influencer marketing.', 'Viña del Mar', 'Valparaíso', ARRAY['contenido-redes'], ARRAY['Community Management', 'Gestión de Redes Sociales', 'Marketing de Influencers', 'Creación de Contenido'], 10, 20, '$$', 'info@socialboost.cl', '+56912345004', 'https://socialboost.cl', true, true, 4.7, 10, NOW(), NOW()),
(gen_random_uuid(), 'VideoPro Chile', 'videopro-chile', 'Producción audiovisual profesional para marcas que quieren destacar. Video corporativo, fotografía de producto y motion graphics.', 'Concepción', 'Biobío', ARRAY['video-fotografia'], ARRAY['Producción Audiovisual', 'Video Corporativo', 'Fotografía Profesional', 'Animación y Motion Graphics'], 6, 12, '$$', 'produccion@videopro.cl', '+56912345005', 'https://videopro.cl', false, false, 4.5, 7, NOW(), NOW()),
(gen_random_uuid(), 'CreativeLab Agency', 'creativelab-agency', 'Agencia de marketing digital especializada en branding y estrategia. Más de 10 años creando experiencias memorables.', 'Santiago', 'Región Metropolitana', ARRAY['publicidad-digital', 'branding-identidad', 'contenido-redes'], ARRAY['Meta Ads (Facebook/Instagram)', 'Branding', 'Community Management', 'Diseño de Logo'], 20, 40, '$$$', 'contacto@creativelab.cl', '+56912345006', 'https://creativelab.cl', true, true, 4.9, 18, NOW(), NOW()),
(gen_random_uuid(), 'Estrategia Plus', 'estrategia-plus', 'Consultoría estratégica y marketing digital. Ayudamos a empresas a crecer con estrategias basadas en datos.', 'Santiago', 'Región Metropolitana', ARRAY['estrategia-consultoria', 'publicidad-digital'], ARRAY['Consultoría de Marketing Digital', 'Estrategia Digital', 'Analytics y Reporting', 'Google Ads (Search/Display/YouTube)'], 5, 10, '$$', 'consultas@estrategiaplus.cl', '+56912345007', 'https://estrategiaplus.cl', true, false, 4.6, 9, NOW(), NOW()),
(gen_random_uuid(), 'Publicidad Impact', 'publicidad-impact', 'Agencia creativa enfocada en campañas publicitarias que generan impacto. RRPP, eventos y comunicación corporativa.', 'Las Condes', 'Región Metropolitana', ARRAY['relaciones-publicas', 'publicidad-digital'], ARRAY['Relaciones Públicas (RRPP)', 'Comunicación Corporativa', 'Organización de Eventos', 'TikTok Ads'], 8, 15, '$$', 'hola@publicidadimpact.cl', '+56912345008', 'https://publicidadimpact.cl', true, true, 4.8, 11, NOW(), NOW()),
(gen_random_uuid(), 'E-Shop Chile', 'eshop-chile', 'Especialistas en tiendas online. Creamos e-commerce rentables con Shopify y WooCommerce.', 'Valparaíso', 'Valparaíso', ARRAY['desarrollo-web', 'publicidad-digital'], ARRAY['E-commerce (Shopify/WooCommerce)', 'Landing Pages', 'Google Ads (Search/Display/YouTube)'], 10, 18, '$$', 'ventas@eshopchile.cl', '+56912345009', '', false, false, 4.4, 6, NOW(), NOW()),
(gen_random_uuid(), 'Diseño Creativo', 'diseno-creativo', 'Estudio de diseño gráfico. Creamos material visual impactante para tu marca.', 'Concepción', 'Biobío', ARRAY['diseno-grafico', 'branding-identidad'], ARRAY['Diseño Gráfico General', 'Material POP', 'Diseño para Redes Sociales', 'Packaging'], 4, 8, '$', 'contacto@disenocreativo.cl', '+56912345010', 'https://disenocreativo.cl', false, false, 4.3, 5, NOW(), NOW());
